# Generated by Django 4.1.7 on 2023-03-13 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_subject_classes_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classes')),
                ('subject', models.ManyToManyField(to='school.subject')),
            ],
        ),
    ]
