# Generated by Django 4.1.7 on 2023-03-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_subject_mark_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cl',
        ),
        migrations.AddField(
            model_name='classes',
            name='student',
            field=models.ManyToManyField(to='school.student'),
        ),
    ]
