# Generated by Django 4.1.7 on 2023-03-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_subject_teacher_remove_classes_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
